#!/bin/bash

set -e # exit on errors

function header {
  echo ""
  echo "$(tput setaf 6)$1$(tput sgr0)"
  echo ""
}

header 'Generating backend documentation ...'
source ./scripts/generate-backend-doc

header 'Generating server documentation ...'
source ./scripts/generate-server-doc
