#!/bin/bash -e

set -e # exit on errors

# print a nicely formated header
function header {
  echo ""
  echo "$(tput setaf 6)$1$(tput sgr0)"
  echo ""
}

# return 1 if global command line program installed, else 0
# example
# echo "node: $(program_is_installed node)"
function program_is_installed {
  # set to 1 initially
  local return_=1
  # set to 0 if not found
  type $1 >/dev/null 2>&1 || { local return_=0; }
  # return value
  echo "$return_"
}

# test if all mandatory programs are installed
function test_all_mandatory_programs {
  missing_programs=()
  passed=true
  programs=('mongod' 'node' 'npm')
  elements=${#programs[@]}

  for ((i=0;i<$elements;i++)); do
    program=${programs[${i}]}
    status=$(program_is_installed ${program})
    if [ $status -eq 0 ] ; then
      missing_programs+=(${program})
      passed=false
    fi
  done

  if [ "$passed" = true ] ; then
    echo "passed"
  else
    echo "the following mandatory programs are not installed: ${missing_programs}"
    exit $1
  fi
}

function install_global_npm_packages {
  packages=('coffee' 'brunch' 'bower' 'foreman' 'forever')
  elements=${#packages[@]}
  coffee="coffee-script"

  for ((i=0;i<$elements;i++)); do
    package=${packages[${i}]}
    status=$(program_is_installed ${package})
    if [ $status -eq 1 ] ; then
      echo "skipping package=${package} because it is already installed"
    else
      if [ $package = "coffee" ] ; then
        package="coffee-script"
      fi
      echo "installing package=${package}"
      npm install -g ${package}
    fi
  done
}

# return 1 if local npm package is installed at ./node_modules, else 0
# example
# echo "gruntacular : $(npm_package_is_installed gruntacular)"
function npm_package_is_installed {
  # set to 1 initially
  local return_=1
  # set to 0 if not found
  ls node_modules | grep $1 >/dev/null 2>&1 || { local return_=0; }
  # return value
  echo "$return_"
}

header "Testing if mandatory programs are installed..."
test_all_mandatory_programs

header "Installing global npm packages"
install_global_npm_packages

header "Installing local npm packages for dummy rest server"
cd rest && npm install && cd ..
echo "done"

header "Installing local npm packages for tests"
cd tests/frontend && npm install && cd ../..
echo "done"

header "Installing local npm packages for DIA-Distributed"
cd web && npm install && cd ..
echo "done"

header "Installing local bower packages for DIA-Distributed"
cd web && bower install && cd ..
echo "done"

header "Creating mandatory folders"
DIRECTORY="./web/logs"
if [ ! -d "$DIRECTORY" ]; then
  cd web && mkdir logs && cd ..
fi
echo "done"

header "Setting up dia_dev database"
mongo localhost:27017/dia_dev ./scripts/setup-database.js
echo "done"

header "Running tests"
source ./scripts/run-tests

echo "done :-)"
