#!/bin/bash

set -e # exit on errors

function header {
  echo ""
  echo "$(tput setaf 6)$1$(tput sgr0)"
  echo ""
}

header 'Running e2e tests ...'
source ./scripts/run-e2e-tests

header 'Running unit tests ...'
source ./scripts/run-unit-tests
