#!/bin/bash

set -e # exit on errors

TSERVER_PID=0
export NODE_ENV=dev

# start server
function start_server {
  printf "Starting testserver ... "
  nf -j Procfile.dev -e test.env start > /dev/null 2>&1 &
  TSERVER_PID=$!
  sleep 10 # wait for server
  printf "OK (PID $TSERVER_PID)\n"
}

# callback to stop server on exit
function stop_server {
  if ps -p $TSERVER_PID > /dev/null; then
    printf "Stopping testserver (PID $TSERVER_PID) ..."
    kill -SIGINT $TSERVER_PID
    sleep 2
    kill 0
  fi
}

# stop server on exit and signals
trap 'stop_server' SIGINT SIGTERM EXIT

# start server
start_server

cd test

echo 'Running tests ...'
npm run e2e

cd ..
